### ISSUE TITLE
It is bad idea to localize developer tools

### ISSUE THREAD

**Issue by ateregulov** [Microsoft/Localization#1]
It will be more difficult to search to seek solutions of problems.

**Comment by aldonetti** [comment]
true in a way, but you are probably thinking about someone who can speak English well like yourself. 
If a user does not have the same abilities, *he/she will not be able to use the tool at all* and the idea behind the localization of our tool (any tool really) is to lower the entry barrier for those users who cannot read/speak English. 
Those users who prefer the English version are free to install it and use it :)

**Comment by ateregulov** [comment]
Do you have a study of the experience of non-English speakers?

I am constantly experiencing the problem of finding the English version. 
Professional speakers recommend to initially use the English versions. 
The phrase "open file" is known to everyone, other terms all the same require studying.

It is misdirected good intentions. It does more harm than good.

**Comment by aldonetti** [comment]
I'm sorry you are having issues finding the English version of our tools - can you please provide an example of where you can only find the localized version and not the English version of a developer product? thanks

**Comment by ateregulov** [comment]
For example https://msdn.microsoft.com/library/ms171868.aspx

On this page, I do not see the information about the 4.7 framework and I do not see a way to get the English version of the page.

**Comment by ateregulov** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/1116637/25009095/32d8500a-206e-11e7-8c7f-5be629cd636a.png)

**Comment by aldonetti** [comment]
thank you for the details - I will check, but I am quite sure it's only a matter of delta between the updates of the English version and of the Localized versions. The English version gets updated first, and as soon as the translations are ready, also the localized versions get the same update. Usually the delta is around two weeks, but as I said I will check.
To get the English version of the page, you either add the locale in the URL (like this - https://msdn.microsoft.com/en-us/library/ms171868.aspx) or you can scroll to the bottom left of the page, click on the Locale selector and select English (United States) - you end up like this
![](https://cloud.githubusercontent.com/assets/2181885/25016491/7cf3de72-2080-11e7-99a0-113372aa3259.png) and you will continue browsing through English pages until you clear your cookies

**Comment by danyeh** [comment]
I want to add that we did do research on experience of non-English speakers. A considerable percentage of customer want the localize version of dev tools. But the percentage of dev tools is lower than IT Pro. IT Pro is lower than information worker.
As a best practice of product design, we usually introduce language setting to allow customer to switch to the language they want other than limit them to one language. For error message, have error code available so it is still searchable in English.
Here is info of how to switch UI language of Visual Studio. https://msdn.microsoft.com/en-us/library/ms246590.aspx
Here is info of how to switch UI language of Visual Studio Code: https://code.visualstudio.com/docs/getstarted/locales
For site language, usually have a Locale selector like Aldo pointed out.
Thank you for your feedback!

**Comment by danyeh** [comment]
I believe we had good discussion. I am closing this 'issue'.

**Comment by aldonetti** [comment]
And I'm sorry I am late to comment on this @ateregulov - I have received the information about that specific page. 

As you may know, we are gradually moving the "home" for our technical documentation from the MSDN Library to [docs.microsoft.com](https://docs.microsoft.com) (DOCS from now on). 
The English content for .NET 4.7 was published to 2 locations on April 5 - MSDN and DOCS - because the team was not sure if they could meet the deadline for publishing to DOCS due to some engineering difficulties. They ultimately were able to publish also on DOCS, so the same documentation is currently published in 2 locations. The Localization team, who works with a delta with respect to the English documentation, is gradually publishing the translated documents for .NET 4.7 on DOCS _only_ (the final destination) because the documents published on MSDN will gradually be redirected to DOCS. The process should be complete in the next few weeks.
The equivalent of that page in the new location should be this one [https://docs.microsoft.com/en-us/dotnet/articles/framework/](https://docs.microsoft.com/en-us/dotnet/articles/framework/)
Any other question please do let us know!
