### ISSUE TITLE
incomplete sentence in source string, no way to translate correctly due to different word order

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#22]
Product is Team Explorer Anywhere

source string is 

"When -auto:External is specified, file contents are merged using the program specified by the"

in Chinese the using adverbial should be placed before the verb (merge). Thus there is no way to translate this sentence correctly due to word order difference.

**Comment by praveeg** [comment]
@jiangsheng - Thanks for raising the issue. I am contacting the product team to clarify the source string. I will update this issue as soon as I get a response.

**Comment by praveeg** [comment]
The incomplete sentence ”_When -auto:External is specified, file contents are merged using the program specified by the_” is a part of a longer help text. Note that besides “_CommandResolve.HelpText2_” there other resource strings with identifiers like “_CommandResolve.HelpText<number>_”. If you sort them in a natural order you’ll see the complete string as:

**When -auto:External is specified, file contents are merged using the program specified by the _TF_MERGE_COMMAND_ environment variable. _TF_MERGE_COMMAND_ must contain the program to launch and the required variables (shown below).  Additional tool-specific options or optional variables may also be specified.  Arguments may be quoted according to Windows-style shell quoting rules.**

Currently, we should translate these strings having in mind that they are parts of a multi-line text. 

This is not ideal for localization due to linguistics of various languages. I created a bug for core team to concatenate all these help text as one string.
