### ISSUE TITLE
Transifex is so hard to find some translation items

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/Localization#29]
Sometimes we take a lot of time to find an item on Transifex.  There are too many categories and too deep in the hierarchy.  Is there any FULL TEXT SEARCH on all categories and all resources?

**Comment by matsurigoto** [comment]
For example, @doggy8088 and I would like to find 'Extract to function in module scope', 'Extract to constant in enclosing scope', and 'Move to a new file' as below 
![messageimage_1537151990123](https://user-images.githubusercontent.com/7632413/45605076-d2c28d80-ba6c-11e8-8791-d8eae83f87bd.jpg)

But we took long time and failed. 
![messageimage_1537153635996](https://user-images.githubusercontent.com/7632413/45605102-f980c400-ba6c-11e8-9188-c9d17f653d16.jpg)

btw, how could we find 'Extract to function in module scope', 'Extract to constant in enclosing scope', and 'Move to a new file' ?

**Comment by danyeh** [comment]
@doggy8088 @matsurigoto , thank you for your feedback! I acknowledge the overall string search experience is painful. 
Regarding those strings on screen, indeed they don't exist in Transifex vscode projects. They are not localizable strings yet. I performed a search in vscode repo, looks like these strings don't exist there as well. Maybe from other toolset.
To drill down, I suggest to open an issue in vscode repo so whoever familiar with the feature or integration can help.
I close the issue here.
