### ISSUE TITLE
MLCP is not mature enough for VS Code

### ISSUE THREAD

**Issue by lyubomirv** [microsoft/Localization#43]
Hello!

I am the main translator of VS Code to Bulgarian. I would like to express my dissatisfaction with MLCP. Note that I have already sent this same message as 'feedback' inside MLCP, but I have not received any response so far.

I really do not understand why VS Code was moved out of Transifex and into this system. The MLCP is clearly immature and in my opinion will not work well for the localisation of VS Code.

In order to be more precise, here are some of the **REALLY ESSENTIAL** features currently missing from MLCP:

- **Overall** list of strings to translate and all strings, along with statistics - how many untranslated, how many translated, votes needed, etc.
- **Similar strings** - Transifex shows suggestions with a percentage of similarity, which is HUGELY important for ensuring translation consistency.
- **Search** - There should be a way to find other strings containing some term/expression and see how they've been translated for consistency, but search can be used for other things too. With the lack of 'similar suggestions' (above point), having search might at least help somewhat.
- **Ability to view and edit my suggestions** - I've already made a few mistakes while translating which I unfortunately submitted. Now I can't find them anywhere to change them.
- **Any way to ask a question** about a particular string or a way to report a problem with it. Github issues are not really a convenient way for that.
- **Better shortcuts** - Ctrl+Right is a really bad shortcut for submit. I frequently use Ctrl+Shift+Left/Right to select whole words while editing texts, and already several times pressing that combination triggered a submit, while I still had half the text not translated. Since I can't edit my suggestion, I can't do anything about that. Meanwhile, there is no shortcut to copy the original text. Etc.
- And so on...

Overall, I think with the current state of this MLCP thing, it would be better to just add a way to for the translators to just download a translation file, edit it with a simple text editor, and then submit it.

Right now, MLCP is blocking, instead of helping, the translation of VS Code. I really cannot work with it for the said issues/lack of features, and this means the Bulgarian (and probably other languages too) translation will probably fall behind, or even be abandoned. If you really care about localising VS Code, please move it back to Transifex until MLCP becomes something that can be worked with (if that's the goal).

Best regards,
Lyubomir Vasilev

**Comment by aldonetti** [comment]
@lyubomirv thank you very much for your feedback - you are right. Some of the points you are making were already raised internally but getting this feedback from the actual users helps to validate the usage scenarios and the asks. I am going to log these requests, which will be prioritised by the engineering team.
The migration cannot be reverted, but I hope it will not be completely blocking - it took me a while to get used to the new tool, and I hope it will be the same for you and others, while we improve MLCP (thanks to your input)
Stay tuned for further developments on this and thank you again for your support to the Bulgarian VScode community!

**Comment by SetTrend** [comment]
I share @lyubomirv's concerns.

I'm not able to search for an item that's currently translated wrong in Visual Studio Code.

Is there a roadmap available for Localization?

**Comment by aldonetti** [comment]
@SetTrend thank you Axel - if you see a term which is incorrect please open an issue here and we'll get it fixed. 
As for Localization plans we don't have a finalized one yet, but we are compiling a prioritized list of top requests, so if you have any other than what @lyubomirv has listed above, please do let me know (with priority).
@lyubomirv we are currently looking to repro and fix the Shortcut issue
thanks!

**Comment by levrik** [comment]
@aldonetti You can't correct strings anymore? I initially started contributing to VS Code translations due to mistakes in translations. It was when the initial Transifex project started. Now, after the move to the new platform, I start seeing a lot of mistakes again. I just wanted to correct them but had to find out that this isn't easily possible anymore.
I'm quite annoyed by the new platform and I don't understand the move to such a unprofessional immature tool. I was a long-time top contributor to the German translation of VS Code but until the project is moved back to Transifex or the new platform has developed sufficiently I will stop contributing. This is unbelievable!

**Comment by aldonetti** [comment]
@levrik Hi Levin, I'm sorry to hear you will not be contributing anymore - unfortunately that's how it is today :( and I know the pain. The best I can do today is to look at the Issues opened here and make the fixes that you suggest, as a workaround until we have found a real solution with the Engineering team.

**Comment by scraimer** [comment]
I just spent a while trying to contribute my own translations. The tool is disheartening, and trying to make my finger not press on CTRL-RIGHT is hard, so I've found myself submitting strings accidentally before I've finished editing them. And I can't go back to fix it after such a mistake!

That means the tool is **actively** contributing to bad data input.

Please fix it or go back to Transifex, which allows all these things.

**Comment by csheesun** [comment]
Hello everyone. I just started to translate strings into Korean. 
As other users, I discovered some flaws of MLCP. 
First, some of my votes and translation that I newly suggested fade away after I press refresh button or Apply button while some of them remain.
Second, I need some engineers or someone who can answer technological inquiry about original string. 
I understand English strings but some strings are technologically recondite or confusing in their sentence structure. 
Anyway MLCP is such an interesting tryout. Thank you all for your dedication!

**Comment by terrysheng** [comment]
Hi @csheesun 
Thanks so much for your valuable feedback and contribution. We will investigate this further, and we will continue to improve MLCP. 
Thanks so much.

**Comment by wojtekmaj** [comment]
I'm really sorry to have to say this, but MLCP is a _disgrace_ to translation community out there. This should never got out in such early development stages.

* Lack of search
* Inability to communicate with original string authors, asking for a context of some kind, and inability to comment
* Inability to suggest many translations - once you submit, the entry is forever gone from the list
* No glossary
* Random order of strings makes it impossible to see the context - there are strings like "focus left editor group" of which I know for a fact that a similar strings (for the left editor group) will appear later - but by this time I'd already have forgotten how exactly I translated the first string.
* No way to navigate to a certain page (with every browser restart, I'm back on the 1st page)

Not only MLCP is not improving in any way, but I feel it's also degrading. Currently there's a bug when after submitting a string, all "Suggest" buttons remain disabled until I refresh the page or execute `document.querySelector('button[disabled]').removeAttribute('disabled'))` after each submit. Being a web developer too, I can see why such bugs are occurring. MLCP is written with outdated tools which were simply not meant to handle apps of this degree of complexity. I wish you all the best, but I do not believe you will be able to make this app substantially better.

I have to agree that in many ways this platform actively contributes to making low quality translations. Not only because it is lacking fundamental tools to make the quality good, but also by scaring away translators who actually care. Today - me. 👋

**Comment by andygonusa** [comment]
@wojtekmaj  Thank you for the feedback. I want you to know that our team, including myself personally, are looking at updating tools and processes with the top requests from the community. We have started with some basics documented here https://github.com/Microsoft/Localization/wiki/MLCPImprovements. In addition, Search, Context, Glossary, and Reference are top features we are currently spec'ing to improve the contributor experience. And yes, we will look into the "Suggest" button issue. Keep an eye on https://github.com/Microsoft/Localization/wiki for updates. 

Best regards.

**Comment by lorthirk** [comment]
Yesterday I wanted to suggest some little (really little, honestly: no game breakers, I swear!) improvements to the Italian localization. I'm a prefectionist, and I always love to contribute Italian localizations for various softwares. As I headed to MLCP I was surprised that there's no Search function. I only wanted to improve one string, and I'm supposed to skip through all the strings hoping to catch the one I want sooner rather than later?

I'll follow this issue hoping to get some improvement notification soon... but honestly, this was a little let down 😟

**Comment by aldonetti** [comment]
Hi @lorthirk - thank you for your comment. Unfortunately we know 😒
Our engineering team is having some challenges at the moment, but the Search feature should be there as soon as they are able to deploy. I'll update you by the end of this week - hopefully with some good news ...
thanks!
Aldo

**Comment by shrijap** [comment]
Hi all, 

I would like to close the loop on this issue - as you may have seen, we have decommissioned MLCP on April 8th, 2020 and are working on a new, more robust community localization platform for you! Please watch the Wiki for more updates on the same, and as always, we greatly appreciate your feedback and valuable contributions - and hope we will continue to see your active participation on the new platform once it goes live!

Shrija

**Comment by glezos** [comment]
For what it's worth, our team at Transifex would be thrilled to offer our platform to the project, and we're open to suggestions of things that could be improved. We'd love to be able to contribute in some way.

Dimitris
Founder, Transifex
