### ISSUE TITLE
Can't contribute to VS Code

### ISSUE THREAD

**Issue by levrik** [Microsoft/Localization#49]
![image](https://user-images.githubusercontent.com/9491603/52563899-ed721600-2e02-11e9-850f-f511460ef162.png)

Where is it? I already contributed a lot on Transifex before.

**Comment by aldonetti** [comment]
hi @levrik no worries - it just happens that _when no contributions are needed, the project disappears from the list_. This is because VSCode was just released. As soon as new strings will be available for translation/voting you will find the "DevTools - VSCode" project in the list again.
thanks for your contributions!
