### ISSUE TITLE
Adding Georgian to MLCP

### ISSUE THREAD

**Issue by tornikenats** [microsoft/Localization#70]
I would like to help to translate Visual Studio Code into Georgian. However, I couldn't find it in the options for Microsoft Localization Community. Would it be possible to add it in?

**Comment by janbaltus** [comment]
Docs here:
https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

Adding Wee Teck for evaluation

**Comment by janbaltus** [comment]
@weeteckt

**Comment by weeteckt** [comment]
Thanks for the interest Tornike Natsvlishvili, I am adding our community manager @aldonetti to provide guidance.

**Comment by aldonetti** [comment]
Sorry for the belated reply @tornikenats 
Thank you for your interest and willingness to help - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
As for other new language requests, I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities! 
thanks! Aldo

**Comment by grigala** [comment]
I'm also willing to help! However, I don't see the use case of having Georgian language in the UI, except maybe for people who are very beginners and do not really speak any other major language(which is very rare in tech community).

Also, having previously worked with UI string translation for as big of a project as Android, I must admit that the language itself is not very technical and finding appropriate translations or synonyms might be a tedious task, additionally, the text might require way more space/characters than in other languages.

**Comment by aldonetti** [comment]
Thank you for your valuable opinions @grigala - there is a lot of truth in what you say. 
It may also be a matter of habit (and preference). The motivations for having a localised UI can be variegated - one guy, who requested another language, was saying that he wanted to enable his mom to write code :) I can also see students benefiting from this and, as you say, beginners in general. 
I guess I cannot find the motivation that works for you.
I certainly agree with you that while translation sounds like a relatively easy task, technical translation can be more challenging, especially because of terminology issues. A lot of the terminology gets created in English, but then would you translate it in your own language or not? and how? Since you have dealt with translations before, I'm sure you know the pain.
That is also why we we don't enable a language at the first request but we wait for at least 5/6 to join... Let's see how it goes for Georgian :)
Cheers!
