### ISSUE TITLE
Add Arabic for Localization

### ISSUE THREAD

**Issue by Ayman97** [microsoft/Localization#80]
Hi
I'd love to contribute in translating in Arabic language, Can you please add it for localization?

**Comment by aldonetti** [comment]
Hello @Ayman97 and thank you very much for your interest and support! Unfortunately, as explained in #69 and #67 , currently there are technical limitations with the handling of Bidirectional scripts in VSCode so we are not able to enable it at the moment 😒
Should anything change on that front, I will make sure to reply to all of these issues, so that you are aware.
Thanks, Aldo

**Comment by Ayman97** [comment]
OK, I'll be waiting :)
