### ISSUE TITLE
Create new Language Pack for VS Code

### ISSUE THREAD

**Issue by tolibrozi** [microsoft/Localization#82]
how can I create a new  language pack (Tajik language) for Visual Studio Code

**Comment by aldonetti** [comment]
Sorry for the belated reply @tolibrozi 
Please mind that due to engineering issues, Bidirectional scripts are not supported, so only the Cyrillic script would be available for Tajik. 
I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by tolibrozi** [comment]
I am very grateful for your support of my intention to translate VS Code into Tajik.I have some experience translating from English to Tajik (Notepad++ -2015, "Вожаномаи компютер -English-Russian-Tajik computer ditionary - 1995").
We will look for volunteers.
thanks,Tolib
